### ISSUE TITLE
Oddball non relevant karma issued?

### ISSUE THREAD

**Issue by mateothegreat** [the-programmers-hangout/aura#1]
> you can find tons of complaints online. For me the straw that broke the camel's back was this one : you can't update only one dependency (transitively) the dev closed it with "not supported, thanks for the feedback" 

![Screen Shot 2020-05-26 at 7 25 49 AM](https://user-images.githubusercontent.com/11623940/82895583-64f98500-9f22-11ea-8f90-59d374493950.png)

**Comment by ItsAzaria** [comment]
Do you have a suggested fix for this? 

Its currently looking for messages with `thanks, thank you, ty` and a mention. 
Its in the works to remove any of those keywords if they're within quotes ("thanks") but do you have any ideas how to further improve the erroneous triggering?

**Comment by mateothegreat** [comment]
We'd want to use some basic NLP.. extract using a matcher then perhaps some sentiment analysis to rate the overall sentence(s) or phrases(s).

You can use `fuzzywuzzy` to do some very crude stuff like token set ratio such as..

```
from fuzzywuzzy import fuzz

choices = ["thanks dude!", "you're awesome thanks man", "blah beep thank boop you"]

print(fuzz.token_set_ratio('thanks', 'youre awesome thanks man'))
print(fuzz.token_set_ratio('thank you', 'thanks for you'))
print(fuzz.token_set_ratio('thank you', 'yo! thank you brospeh'))
```
..which outputs..

```
(venv)  yomateod@heman  ~/workspace/work/nlp  (⎈ |dev-1:default) python wuzzy.py
100
78
100
```

I'll whip up an NLP pipeline later today for ya!

**Comment by ghost** [comment]
1) In the current development branch, thanks that are contained within **""** are filtered out with a seperate regex. 

2) Levensthein difference sounds fine, when applied to the keyword itself. Obviously shouldn't be applied to ty or similiar low length keywords just because there's way too many things that are very close in distance to a two char length string. Seems like token.set_ratio does this by splitting the string into one intersection and one remainder part and taking a ratio from those two. Took a look at the source and I'm not quite sure why that last ratio is also a 100.

3) NLP was always planned to be introduced at later date, i'd like the possibility of turning on NLP or turning it off, if you don't want to use NLP for aura.

**Comment by ghost** [comment]
How's this by the way?
https://github.com/huggingface/transformers
Seems pretty good and easy to use, i'll try integrating it into aura maybe?

**Comment by ghost** [comment]
related issue: https://github.com/arkencl/aura/issues/57
all further discussion please in the main repository if there is need.
